language: node_js

node_js:
 - 9.2.0

branches:
  only:
  - master

install: npm install

before_script:
- git config --global user.name "LuizAdolphs"
- git config --global user.email "luiz.adolphs@gmail.com"
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script: npm run build
